creation_rules:
  # Dev
  - path_regex: cardano/vasil-qa/*
    hc_vault_transit_uri: "https://vault.world.dev.cardano.org/v1/sops/keys/dev"
  # Ops
  - path_regex: patroni/infra*
    hc_vault_transit_uri: "https://vault.world.dev.cardano.org/v1/sops/keys/ops"
  - path_regex: db-sync/vasil-qa*
    hc_vault_transit_uri: "https://vault.world.dev.cardano.org/v1/sops/keys/ops"
